### ISSUE TITLE
Some stuffs.

### ISSUE THREAD

**Issue by Distortionn** [Witch-hue/Sea-Of-Honor#1]
You obviously know some of the errors that seem to be appearing in the log. 
One of them seems to be mostly related to the marking on people (Or on yourself)

It marks people who got the fear on them and un-marks them but it doesn't seem to be doing that when you get the fear. The mark remains after its placed on you.

Next to that (for me.) the only thing that seems to be missing are the following call-outs:
- In > Out > In
- Out > In > Out
- In > Out > Out
- Out > In > In

You do get to see the circles with the flowers for it and such, but it doesn't give you a message saying if its either of those four, which would make it a lot easier.

Next to that everything seems to be working spot on. Only suggestion I would have myself is to well fix the first two things whenever possible and perhaps turn off the mob announcements/flowers for the mobs. Pretty much just the boss that is important.

Wave below 30% doesn't seem to be included either, but not a biggie since they happen after the first 2 ins or outs.

Thanks in advance though, keep it up :)

**Comment by Witch-hue** [comment]
:p I did say it was incomplete and a work in progress in the read me, and that the module it self will toss errors.


Seeing that I have a limited amount of times I can test the module each week it's a slow progress.

My next push should be doing the in out notices, and I was gonna possibley add a feature to disable the flower patterns because it can be a little hard on the eyes.
